name: Update TLEs
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download TLEs
        working-directory: ./TLEs
        run: wget --backups=1 -i ../links.txt && rm *.1
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update" || true
          git push || true
